# Generated by Django 6.0 on 2026-01-04 13:34

import django.core.validators
import django.db.models.deletion
import driveManageSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教练姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '教练',
                'verbose_name_plural': '教练管理',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default=driveManageSystem.models.Student.generate_student_id, max_length=20, unique=True, verbose_name='学员编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('register_date', models.DateField(verbose_name='报名日期')),
                ('car_type', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2')], max_length=10, verbose_name='报考车型')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总费用')),
                ('paid_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='已缴费')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='欠费')),
                ('status', models.CharField(choices=[('报名中', '报名中'), ('科目一', '科目一'), ('科目二', '科目二'), ('科目三', '科目三'), ('科目四', '科目四'), ('毕业', '毕业')], default='报名中', max_length=20, verbose_name='当前状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='转入时间')),
                ('start_training_date', models.DateField(blank=True, null=True, verbose_name='上车时间')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='结业时间')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='现金收取金额')),
                ('prepay_coach_date', models.DateField(blank=True, null=True, verbose_name='预付教练时间')),
                ('prepay_coach_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预付教练金额')),
                ('bank_transfer1_date', models.DateField(blank=True, null=True, verbose_name='银行转账1时间')),
                ('bank_transfer1_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='银行转账1金额')),
                ('bank_transfer2_date', models.DateField(blank=True, null=True, verbose_name='银行转账2时间')),
                ('bank_transfer2_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='银行转账2金额')),
                ('bank_transfer3_date', models.DateField(blank=True, null=True, verbose_name='银行转账3时间')),
                ('bank_transfer3_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='银行转账3金额')),
                ('pay_coach_date', models.DateField(blank=True, null=True, verbose_name='支付教练时间')),
                ('pay_coach_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='支付教练金额')),
                ('car_number', models.CharField(blank=True, max_length=20, verbose_name='车号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driveManageSystem.coach', verbose_name='教练')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员管理',
                'ordering': ['-register_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='收费日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('receiver', models.CharField(default='系统', max_length=50, verbose_name='收款人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='driveManageSystem.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '收费记录',
                'verbose_name_plural': '收费记录',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CoachSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_month', models.CharField(max_length=7, verbose_name='结算月份')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应结算金额')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driveManageSystem.coach', verbose_name='教练')),
                ('graduated_students', models.ManyToManyField(to='driveManageSystem.student', verbose_name='毕业学员')),
            ],
            options={
                'verbose_name': '教练结算',
                'verbose_name_plural': '教练结算',
            },
        ),
    ]
