"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from pathlib import Path

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ========== 数据库配置 - 持久化版本 ==========
def get_database_config():
    """智能获取数据库配置"""
    
    # 优先级1：环境变量指定的路径
    env_db_path = os.environ.get('DJANGO_DB_PATH')
    if env_db_path and os.path.exists(os.path.dirname(env_db_path)):
        print(f"[设置] 使用环境变量数据库: {env_db_path}")
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': env_db_path,
                'OPTIONS': {
                    'timeout': 30,  # 增加超时时间
                }
            }
        }
    
    # 优先级2：打包环境
    if getattr(sys, 'frozen', False):
        # exe所在目录的data文件夹
        app_dir = os.path.dirname(sys.executable)
        default_db = os.path.join(app_dir, 'data', 'db.sqlite3')
        
        # 确保目录存在
        os.makedirs(os.path.dirname(default_db), exist_ok=True)
        
        print(f"[设置] 使用打包环境数据库: {default_db}")
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': default_db,
                'OPTIONS': {
                    'timeout': 30,
                }
            }
        }
    
    # 优先级3：开发环境
    dev_db = BASE_DIR / 'db.sqlite3'
    print(f"[设置] 使用开发环境数据库: {dev_db}")
    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': dev_db,
        }
    }

DATABASES = get_database_config()

# ========== 静态文件配置 ==========
STATIC_URL = 'static/'

# 如果是打包环境，调整静态文件路径
if getattr(sys, 'frozen', False):
    # 打包环境：使用临时目录
    STATIC_ROOT = os.path.join(sys._MEIPASS, 'static') if hasattr(sys, '_MEIPASS') else None
else:
    # 开发环境
    STATIC_ROOT = BASE_DIR / 'staticfiles'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+_25pj99ctyks8@+n)kv7$*8js$hf$g2!_svqzbj-idr6vphbr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'driveManageSystem',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
