# Generated by Django 6.0 on 2026-01-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pay_coach_amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pay_coach_date',
        ),
        migrations.AddField(
            model_name='coachsettlement',
            name='prepay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预付教练金额'),
        ),
        migrations.AddField(
            model_name='coachsettlement',
            name='prepay_date',
            field=models.DateField(blank=True, null=True, verbose_name='预付教练时间'),
        ),
        migrations.AddField(
            model_name='student',
            name='prepay_coach_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预付教练金额'),
        ),
        migrations.AddField(
            model_name='student',
            name='prepay_coach_date',
            field=models.DateField(blank=True, null=True, verbose_name='预付教练时间'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_pay_coach_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='第二次支付教练金额'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_pay_coach_date',
            field=models.DateField(blank=True, null=True, verbose_name='第二次支付教练时间'),
        ),
    ]
